<%-- 
    Document   : MainMenu
    Created on : Oct 8, 2022, 7:57:33 PM
    Author     : ASUS
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page import="DAO.HealthDAO"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href = "./css/termconditions.css"/>
        <%@ include file = "headfootlink.jsp"%>
        <title>Nutrition</title>

    </head>
    <body>
        <%@ include file="header.jsp" %>
        <div>
            <div class="body">
                <h1 style="font-weight: 700;">Nutrition Terms and Conditions of Use</h1>
                <p>Effective Date: December 18, 2022</p>
                <p><i>Welcome to Nutrition. These Terms and Conditions of Use apply and govern your use of our website and mobile application (the “App”) and are designed to create a positive, law-abiding community of our users. By using MyFitnessPal, you are agreeing to all the terms and conditions below.</i></p>
                <p>Nutrition, Inc. and any successor entity (referred to throughout as “Nutrition,” “we” or “us”), offers a variety of content and services through the MyFitnessPal website and App (collectively, the “Services”).</p>
                <p style="text-transform: lowercase;">THESE TERMS INCLUDE A BINDING ARBITRATION CLAUSE AND A CLASS ACTION WAIVER IN SECTION 14. THIS PROVISION AFFECTS YOUR RIGHTS TO RESOLVE DISPUTES WITH NUTRITION AND YOU SHOULD REVIEW IT CAREFULLY. YOUR CHOICE TO MAINTAIN AN ACCOUNT, ACCESS OR USE THE SERVICES (REGARDLESS OF WHETHER YOU CREATE AN ACCOUNT WITH US) CONSTITUTES YOUR AGREEMENT TO THESE TERMS AND OUR PRIVACY POLICY, WHICH IS INCORPORATED INTO THE TERMS. IF YOU DISAGREE WITH ANY PART OF THE TERMS, THEN YOU ARE NOT PERMITTED TO USE OUR SERVICES.</p>
                <p>Please note the summaries in shaded boxes at the top of most sections are provided to make the Terms easier to understand. In the event of a conflict between any summary and any section of the Terms, the Terms will control.</p>
                <p>Please feel free to contact us through our Support Team if you have any questions or suggestions.</p>
                <h2>1. Use of the Services and Your Account</h2>
                <h3>1.1 Who can use the Services</h3>
                <p>You must be at least 18 years old to use the Services.</p>
                <p>You must be at least 18 to use the Services (unless otherwise specified in the International Terms section applicable to specific jurisdictions). No individual under the age of 18 may use the Services, provide any Personal Data (as that term is defined in the Privacy Policy) to us, or otherwise submit Personal Data through the Services (e.g., a name, address, telephone number, or email address).</p>
                <h3>1.2 Your Account</h3>
                <p><i>You may need to create a Nutrition account to access the Services, and it's important that you keep your account accurate and up-to-date (particularly your email address - if you ever forget your password, a working email address is often the only way for us to verify your identity and help you log back in).</i></p>
                <p>You may need to register for a Nutrition account to access or use certain Services. Your account may also automatically provide you access and means to use any new Services.</p>
                <p>When you create an account for any of our Services, you must provide us with accurate and complete information as prompted by the account creation and registration process, and keep that information up to date. Otherwise, some of our Services may not operate correctly, and we may not be able to contact you with important notices.</p>
                <p>You are responsible for maintaining the confidentiality of any and all actions that take place while using your account, and must notify our Support Team right away of any actual or suspected loss, theft, or unauthorized use of your account or account password. We are not responsible for any loss that results from unauthorized use of your username and password.</p>
                <h3>1.3 Service Updates, Changes and Limitations</h3>
                <p><i>Our Services are constantly evolving. With the launch of new products, services, and features, we need the flexibility to make changes, impose limits, and occasionally suspend or terminate certain Services. We may also update our Services, which might not work properly if you don't install the updates.</i></p>
                <p>The Services change frequently, and their form and functionality may change without prior notice to you.</p>
                <p>We may provide updates (including automatic updates) for certain Services as and when we see fit. This may include upgrades, modifications, bug fixes, patches and other error corrections and/or new features (collectively, “Updates”). Certain portions of our Services may not properly operate if you do not install all Updates. You acknowledge and agree that the Services may not work properly if you do not allow such Updates and you expressly consent to automatic Updates. Further, you agree that the Terms (and any additional modifications of the same) will apply to any and all Updates to the Services. We may change, suspend, or discontinue any or all of the Services at any time, including the availability of any product, feature, database, or Content. In addition, we have no obligation to provide any Updates or to continue to provide or enable any particular features or functionality of any Service. We may also impose limits on certain Services or restrict your access to part or all of the Services without notice or liability.</p>
                <h3>1.4 Service Monitoring and Suspension</h3>
                <p><i>We reserve the right to refuse to provide the Services to anyone, and can monitor, terminate or suspend your account or access to the Services at any time.</i></p>
                <p>We reserve the right, but have no obligation, to monitor any accounts and/or activities conducted through or in any way related to the Services (including inviting a fellow user into a community or group), as well as any user’s use of or access to Personal Data, and profiles of other users.</p>
                <p>We may also deactivate, terminate or suspend your account or access to certain Services at any time: (1) if we, in our sole discretion, determine you are or have been in violation of these Terms or the spirit thereof (as highlighted in our Community Guidelines), (2) if we, in our sole discretion, determine you have created risk or possible legal exposure for Nutrition, the general public, any third party, or any user of our Services, (3) in response to requests by law enforcement or other government agencies, (4) upon discontinuation or material modification of any Services, or (5) due to unexpected technical issues or problems. We will endeavor to notify you by email or the next time you attempt to access your account after any such deactivation, termination or suspension.</p>
                <h3>1.5 Security</h3>
                <p><i>Please let us know right away if you believe your account has been hacked or compromised.</i></p>
                <p>We care about the security of our users. While we work hard to protect the security of your Personal Data, User-Generated Content, and account, we cannot guarantee that unauthorized third parties will not be able to defeat our security measures. Please notify our Support Team immediately of any actual or suspected breach or unauthorized access or use of your account.</p>
                <h2>2. Ownership and Use of Content</h2>
                <h3>2.1 Definitions</h3>
                <p>Content is what shows up in-app or on the website when you use our Services. User-Generated Content is any Content that is created by you or other users, and Nutrition Content is all other Content.</p>
                <h3>2.2 Ownership</h3>
                <p><i>You own the Content that you create, and we own the Content that we create.</i></p>
                <p>All Nutrition Content and all copyright, trademarks, design rights, patents and other intellectual property rights (registered and unregistered) in and on the Services belong to Nutrition and/or its partners or applicable third parties. Each user retains ownership, responsibility for, and/or other applicable rights in the User-Generated Content that he/she creates, but grants a license of that User Generated Content to Nutrition as explained in Section 2.5 below. Nutrition and/or its partners or third parties retain ownership, responsibility for and/or other applicable rights in all Nutrition Content. Except as expressly provided in the Terms, nothing grants you a right or license to use any Nutrition Content, including any content owned or controlled by any of our partners or other third parties. You agree not to duplicate, publish, display, distribute, modify, or create derivative works from the material presented through the Services unless specifically authorized in writing by us.</p>
                <h3>2.3 Our License to You</h3>
                <p><i>You are welcome to access and use the Nutrition Content and Services. We work hard to provide a great experience for our users, so please respect our intellectual property rights and only use the Nutrition Content and Services as intended. This includes not using any Nutrition Content or Services for commercial purposes without our permission. We do have APIs and other tools you can use to help create your own apps and products. Contact us to find out more.</i></p>
                <p>Subject to your compliance with these Terms, we grant you a limited, revocable, personal, non-transferable, and non-exclusive right and license to access and use the Services and Subject to your compliance with these Terms, we grant you a limited, revocable, personal, non-transferable, and non-exclusive right and license to access and use the Services and Nutrition Content for your own personal, noncommercial purposes, provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, sell, assign, sublicense, grant a security interest in, transfer or otherwise commercially exploit any right in the Subject to your compliance with these Terms, we grant you a limited, revocable, personal, non-transferable, and non-exclusive right and license to access and use the Services and Nutrition Content for your own personal, noncommercial purposes, provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, sell, assign, sublicense, grant a security interest in, transfer or otherwise commercially exploit any right in the Subject to your compliance with these Terms, we grant you a limited, revocable, personal, non-transferable, and non-exclusive right and license to access and use the Services and MyFitnessPal Content for your own personal, noncommercial purposes, provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, sell, assign, sublicense, grant a security interest in, transfer or otherwise commercially exploit any right in the Subject to your compliance with these Terms, we grant you a limited, revocable, personal, non-transferable, and non-exclusive right and license to access and use the Services and Nutrition Content for your own personal, noncommercial purposes, provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, sell, assign, sublicense, grant a security interest in, transfer or otherwise commercially exploit any right in the Nutrition Content or Services.Nutrition Content or Services. Content or Services. Content or Services. Content for your own personal, noncommercial purposes, provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, sell, assign, sublicense, grant a security interest in, transfer or otherwise commercially exploit any right in the Nutrition Content or Services.</p>
                <h3>2.4 Acceptable Usage Guidelines</h3>
                <p> If you would like to link to our Services on your website or App, please follow these rules: (i) any link to the Services must be a text only link clearly marked “Nutrition” (without the use of any other trademark, logo copyright or any other intellectual property asset owned or controlled by Nutrition) or in some other format directed by us, (ii) the appearance, position and other aspects of the link may not damage or dilute the goodwill associated with our marks, (iii) the link must “point” to the root domain name of the Services and not to other pages within the Services, (iv) the appearance, position and other attributes of the link may not create the false appearance that your organization or entity is sponsored by, affiliated with, or associated with Nutrition, (v) when selected, the link must display the Service on full-screen and not within a “frame” on the linking website or service, and (vi) we reserve the right to revoke its consent to the link at any time and in its sole discretion, and upon our notification to you of such revocation of consent, you agree to promptly remove the relevant link.</p>
                <h3>2.5 Your License to Us</h3>
                <p><i>When you post Content in connection with the Services, it belongs to you - however, you're giving us permission to use that Content in connection with our Services and make the Content available to others. We can edit or remove your Content from our Services at any time for any reason. Don't post any Content that is not yours or that you do not have permission to post.</i></p>
                <p>When you provide User-Generated Content to Nutrition through the Services, you grant us and our users a non-exclusive, irrevocable, royalty-free, freely transferable, sublicensable, worldwide right and license to use, host, store, cache, reproduce, publish, display (publicly or otherwise), perform (publicly or otherwise), distribute, transmit, modify, adapt (including, without limitation, in order to conform to the requirements of any networks, devices, services, or media through which the Services are available), commercialize, create derivative works of, and otherwise exploit such User-Generated Content in connection with any and all Services. You acknowledge and agree that: (a) we have the right to arrange the posting of User-Generated Content in any way we desire; (b) we have no obligation to provide you with any credit when using your User-Generated Content, but if we choose to provide you with credit, the size and placement of the credit is at our sole discretion; and (c) you are not entitled to any compensation or other payment from us in connection with the use of your User-Generated Content.</p>
                <p>The rights you grant in this license are for the limited purposes of allowing MyFitnessPal to operate and allow other users to use the Services in accordance with their functionality, improve the Services, and develop new Services. Notwithstanding the above, we will not make use of any of your User-Generated Content in a manner that is inconsistent with our Privacy Policy.</p>
                <p>We reserve the right to monitor, remove or modify User-Generated Content for any reason and at any time, including User-Generated Content we believe violates these Terms, the Community Guidelines, and/or our policies.</p>
                <p>You agree you will respect the intellectual property rights of others. You represent and warrant you have all the necessary rights to grant MyFitnessPal the foregoing license for all User-Generated Content you submit in connection with the Services and will indemnify us for any breach of this representation and warranty.</p>
                <h3>2.6 Spreading the Word</h3>
                <p><i>If you share someone else's Personal Data with us, you must first get their permission.</i></p>
                <p>We hope you enjoy using our Services and encourage you to share your enthusiasm for them with your friends. If you elect to use the features in our Services to tell a friend about the Services, we will ask you to provide your friend’s email address or social media profile, which we may then use to contact your friend about the Services. We may store the information you provide for a period of time, but we will not post this information publicly. You represent and warrant that you are authorized to provide any third-party contact information that you provide to us for referrals and will indemnify us for any breach of this representation and warranty.</p>
                <h3>2.7 Content Retention</h3>
                <p><i>Please keep in mind that when you make something publicly available on the Internet, it becomes practically impossible to take down all copies of it in the future.</i></p>
                <p>Following termination of your account, or if you remove any User-Generated Content from the Services, we may retain your User-Generated Content for a commercially reasonable period of time for backup, archival, or audit purposes, or as otherwise required or permitted by law. Further, Nutrition and its users may retain and continue to use, store, display, reproduce, share, modify, create derivative works, perform, and distribute any of your User-Generated Content that otherwise has been stored or shared through the Services. The license to your User-Generated Content therefore continues even if you stop using the Services. When you post something publicly, others may choose to comment on it, making your Content part of a social conversation. For more information, please review our Privacy Policy.</p>
                <h2>3. Community Guidelines</h2>
                <h3>3.1 Interactive Areas</h3>
                <p><i>Our Services often contain community features. When you post content through these features that content may become public. We may, but do not always, monitor our community features, and ultimately you are responsible for your interactions with other users. Please use good judgment and play fair.</i></p>
                <p>Some of our Services may include reviews, discussion forums, conversation pages, blogs or other interactive areas or social features that allow you and other users to post User-Generated Content and interact with one another (“Interactive Areas”). You are solely responsible for your use of the Interactive Areas and for any User-Generated Content you post, including the transmission, accuracy and completeness of the User-Generated Content. As the Interactive Areas are often public, you understand your User-Generated Content may be made and remain public. You should, accordingly, never post any Personal Data in an Interactive Area.</p>
                <p>We are entitled, but have no obligation, to monitor our community features. You are solely responsible for your interactions with other users, whether online or in person, including but not limited to comments, challenges, and friendly competition. We assume no responsibility or liability for any loss or damage resulting from any interaction with other users who employ the Services, individuals you meet through the Services, or individuals who find you because of Content posted on, by or through the Services. MyFitnessPal is under no obligation to become involved in and disclaims all liability related to any disputes between its users and you release MyFitnessPal from all responsibility and liability arising out of or in connection with such dispute.</p>
                <h3>3.2 Community Guidelines</h3>
                <p><i></i></p>
                <p>Our Services are intended to be a safe and supportive environment to help you reach your fitness and wellness goals. You cannot use our services to post inappropriate material, harass people, send spam, violate intellectual property rights, or act inappropriately. Be reasonable and act responsibly.</p>
                <p>Our Services are intended to create a safe and supportive community for all users. To maintain a safe and positive environment, we require everyone to agree to and follow certain rules (the “Community Guidelines”) when posting User-Generated Content and using the Services. Our Community Guidelines are based in many instances on principles of applicable law. Violations of our Community Guidelines may expose you to criminal charges and civil liability. By using the Services you agree that your User-Generated Content and use of the Services, including without limitation the Interactive Areas, will not violate the Community Guidelines. If you violate the Community Guidelines, we reserve the right to terminate your access to the Services.</p>
                <h3>3.3 Reporting Objectionable User-Generated Content</h3>
                <p><i>People do post inappropriate content on user-generated content sites. We do our best to keep the community safe and secure (users respecting the Community Guidelines helps), but you still might run into bad content before we have a chance to take it down. If you spot anything objectionable, please let us know.</i></p>
                <p>While we require all of our users to comply with the Community Guidelines and reserve the right to monitor for violations, we ultimately cannot guarantee all users will comply with the Community Guidelines or these Terms at all times. If you believe any Content submitted to our Services violates the Community Guidelines, or if you know or suspect someone is misusing your User-Generated Content, please report it to the Support Team. We have the right, but not the obligation, to review and take action or remove any User-Generated Content you report. You understand and acknowledge that when you access or otherwise use the Services, you may be exposed to User-Generated Content from a variety of sources, and we are not responsible for the accuracy, usefulness, safety, legality, appropriateness, or intellectual property rights of or relating to such User-Generated Content.</p>
                <h2>4. Intellectual Property/ DMCA</h2>
                <p>If you believe User-Generated Content or MyFitnessPal Content infringes copyright or trademark under U.S. or other national law, please notify us immediately using the contact information provided herein. It is our policy to investigate any allegations of infringement brought to our attention. Please provide us with the following information in your notice of a suspected violation:</p>
                <p>
                <ul>
                    <li>Identification of the material being infringed.</li>
                    <li>Identification of the material that is claimed to be infringing, including its location, with sufficient detail so that we are capable of finding it and verifying its existence.</li>
                    <li>Contact information for the notifying party (the “Notifying Party”), including name, address, telephone number, and email address.</li>
                    <li>A statement that the Notifying Party has a good faith belief that the material is not authorized by the owner, its agent or law.</li>
                    <li>A statement made under penalty of perjury that the information provided in the notice is accurate and that the Notifying Party is authorized to make the complaint on behalf of the owner.</li>
                    <li>A physical or electronic signature of a person authorized to act on behalf of the owner of the material that has been allegedly infringed.</li>
                </ul>
                </p>
                <p>Your notice must be signed (physically or electronically) and must be addressed as follows:</p>
                <p>You acknowledge that if you fail to comply with all of the requirements of this section, your notice may not be valid. Some information provided in a notice of infringement may be forwarded to the user who posted the allegedly infringing content. In the U.S., under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability. </p>
                <h2>5. Third Party Links and Services</h2>
                <p><i>Our Services may link to, interact with or be available on third-party services or products such as social media and third-party devices. If you access such third-party services or products, be aware that different terms and privacy policies apply to your usage of such services.</i></p>
                <h3>5.1 Social Networking and Logins</h3>
                <p>You may enable or log in to the Services via various online third-party services, such as social media and social networking services like Facebook (“Social Networking Services”). To take advantage of these features and capabilities, we may ask you to authenticate, register for, or log into Social Networking Services on the websites of their respective providers. As part of this integration, the Social Networking Services will provide us with access to certain information you have provided to them, and we will use, store, and disclose such information in accordance with our Privacy Policy. Please remember the way Third Party Services (including Social Networking Services) use, store, and disclose your information is governed solely by the policies of those Third Party Services, and we have no liability or responsibility for the privacy practices or other actions of any third-party website or service that may be enabled within the Services. In addition, we are not responsible for the accuracy, availability, or reliability of any information, content, goods, data, opinions, advice, or statements made available in connection with Social Networking Services. As such, we are not liable for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such Social Networking Services.</p>
                <h3>5.2 Third-Party Applications</h3>
                <p>You may be able to access certain third-party links, applications, content, services, promotions, special offers, or other events or activities (“Third-Party Applications”) via our Services. If you choose to access these Third-Party Applications, you may be requested to log-in and sync your accounts with such applications. You are in no way obligated to use any Third-Party Applications, your access and use of such applications is entirely at your own risk, and we have no associated liability. In addition, we are not responsible for the accuracy, availability, or reliability of any information, content, goods, data, opinions, advice, or statements made available by any Third-Party Applications. As such, we are not liable for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such Third-Party Applications.</p>
                <h3>5.3 Third Party Products</h3>
                <p>Our Services may be accessed on third-party devices or other products (“Third Party Products”), and your ability to use certain features of the Services may require you to purchase Third-Party Products (e.g., fitness trackers, smart scales, etc.). While we may recommend, promote, or market the products of certain partners, we have no responsibility for your acquisition or use of any Third-Party Products, and we do not guarantee that Third-Party Products will function with the Services or will be error-free. We hereby disclaim liability for all Third-Party Products, including any Third-Party Products offered by our partners.</p>
                <h2>6. Mobile Services</h2>
                <p><i>While we strive to make the Services available on many platforms, we can't guarantee that the App is compatible with your device (though please let Customer Support know if you have a question or problem; we want to help). If you use the App, your standard data and messaging rates will apply, and the rules of the app store from which you are downloading will also apply.</i></p>
                <h3>6.1 Wireless Carrier and Device Considerations</h3>
                <p>To use or access our App, you will need a compatible device. We cannot guarantee the App will be compatible with, or available on, your device. We do not charge for use of the App. Your phone company’s normal messaging, data, and other rates and fees, however, will still apply. You may be required pay fees to access certain special features and content included in our Premium Subscriptions (as described in Section 7).</p>
                <h2>7. No Warranties</h2>
                <p>EXCEPT WHERE PROHIBITED BY LAW, MYFITNESSPAL EXPRESSLY DISCLAIMS ALL WARRANTIES, REPRESENTATIONS AND GUARANTEES OF ANY KIND, WHETHER ORAL OR WRITTEN, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT TO THE FULLEST EXTENT PERMISSIBLE UNDER THE LAW. THE SERVICES AND ALL CONTENT ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” WITH ALL FAULTS BASIS. Without limiting the foregoing, you understand that, to the maximum extent permitted by applicable law, we make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness, availability, or reliability of any of the Services or any Content. To the maximum extent permitted by applicable law, we do not warrant that (i) the Services will meet your requirements or provide specific results, (ii) the operation of the Services will be uninterrupted, virus- or error-free or free from other harmful elements or (iii) errors will be corrected. Any oral or written advice provided by our agents or us does not and will not create any warranty. To the maximum extent permitted by applicable law, we also make no representations or warranties of any kind with respect to any Content; User-Generated Content, in particular, is provided by and is solely the responsibility of the users providing that Content. No advice or information, whether oral or written, obtained from other users or through the Services, will create any warranty not expressly made herein. You therefore expressly acknowledge and agree that use of the Services is at your sole risk and that the entire risk as to satisfactory quality, performance, accuracy and effort is with you.</p>
                <h2>8. International Terms</h2>
                <p>If you are not a United States resident and you are accessing our Services from outside the United States, you agree to transfer certain information outside your location to us, and that you will follow all the laws that apply to you.</p>
                <p>We provide our Services for a global community of users. Our servers and operations are, however, located primarily in the United States, and our policies and procedures are based primarily on United States law. Because of this, the following provisions apply specifically to users located outside of the United States: (i) you consent to the transfer, storage, and processing of your information, including but not limited to User-Generated Content and any Personal Data, to and in the United States and/or other countries; (ii) if you are using the Services from a location embargoed by the United States, or are on the United States Treasury Department’s list of “Specially Designated Nationals,” you are not authorized to access or make use of the Services; and (iii) you agree to comply with all local laws, rules, and regulations including, without limitation, all laws, rules, and regulations in effect in the location in which you reside and the location from which you access the Services. The Services are not intended for distribution to, or use by, any person or entity in any jurisdiction or location where such distribution or use would be contrary to law or regulation, or which that would subject MyFitnessPal or its affiliates to any registration requirement within such jurisdiction or location.</p>
                <p>The names used for countries or regions in these Terms, the Privacy Policy and any associated features or documentation are based on the United Nations Terminology Database.</p>
                <h2>9. Miscellaneous</h2>
                <p>You agree that no joint venture, partnership, employment, or agency relationship exists between you and us as a result of the Terms or your use of the Services. The Terms constitute the entire agreement between you and us with respect to your use of the Services.</p>
                <p>Our failure to exercise or enforce any right or provision of the Terms does not constitute a waiver of such right or provision. If any provision of the Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of the Terms remain in full force and effect.</p>
                <p>You may not assign, delegate, or otherwise transfer your account or your obligations under these Terms without our prior written consent. We have the right, in our sole discretion, to transfer or assign all or any part of our rights under these Terms and will have the right to delegate or use third-party contractors to fulfill our duties and obligations under these Terms and in connection with the Services.</p>
                <p>Our notice to you via email, regular mail, or notices or links displayed in connection with the Services constitutes acceptable notice to you under the Terms. We are not responsible for your failure to receive notice if email is quarantined by your email security system (e.g., “junk” or “spam” folder) or if you fail to update your email address. Notice will be considered received forty-eight hours after it is sent if transmitted via email or regular mail. In the event that notice is provided via links displayed in connection with the Services, then it will be considered received twenty-four hours after it is first displayed.</p>
                <h2>10. Contact Us</h2>
                <p>If you have any feedback, questions or comments about the Services, please contact our Support Team as detailed <a href= "mailto:thinhnlqce161130@fpt.edu.vn">HERE</a> by email or by mail</p>
                <p></p>
                <p></p>
            </div>
        </div>
        <jsp:include page="footer.jsp"></jsp:include>
        <script src="scripts/headfootscript.js"></script>
    </body>
</html>
